if (!require("BiocManager", quietly = TRUE))
  install.packages("BiocManager")
BiocManager::install(version = "3.15")
BiocManager::install("TCGAbiolinks")
BiocManager::install("dplyr")
BiocManager::install("SummarizedExperiment")
BiocManager::install("edgeR")
BiocManager::install("tidyverse")
library(TCGAbiolinks)
library(dplyr)
library(SummarizedExperiment)
library(edgeR)
library(tidyverse)
